# https://github.com/rubocop-hq/rubocop-rails
# https://github.com/rubocop-hq/rubocop-rspec
require:
  - rubocop-rails
  - rubocop-rspec

#
# Specific excludes & includes
#

# Okay to have long examples in feature tests, there are usually many steps
RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*.rb'

# Ignore LineLength for config files (e.g. with long secret strings)
Layout/LineLength:
  Exclude:
    - 'config/**/*.rb'

# Ignore "Block has too many lines" for specs, `RSpec.describe` blocks can be long
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# Okay to have more than one expectation in a single block, default: 1
RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/*.rb'

# Only check "Missing top-level class documentation comment" for models
Style/Documentation:
  Include:
    - 'app/models/*.rb'

# Ignore "Prefer $CHILD_STATUS from the stdlib 'English' module (don't forget to require it) over $?"
Style/SpecialGlobalVars:
  Exclude:
    - 'lib/**/*.rake'

#
# Ignoring entire rules
#

# Ignore "Prefer single-quoted strings when you don't need string interpolation or special symbols"
Style/StringLiterals:
  Enabled: false

# Ignore "Avoid instance variables – use let, a method call, or a local variable (if possible)"
RSpec/InstanceVariable:
  Enabled: false

# Ignore "Missing frozen string literal comment"
Style/FrozenStringLiteralComment:
  Enabled: false

# Ignore "Prefer not_to over to_not"
RSpec/NotToNot:
  Enabled: false

# Ignore "Add parentheses to nested method call"
Style/NestedParenthesizedCalls:
  Enabled: false

# Ignore "Use ! instead of not"
Style/Not:
  Enabled: false

# Ignore "Use `%i` or `%I` for an array of symbols"
Style/SymbolArray:
  Enabled: false

# Ignore "Gems should be sorted in an alphabetical order within their section of the Gemfile"
Bundler/OrderedGems:
  Enabled: false

# Ignore "Please use Rails.root.join('path/to') instead"
Rails/FilePath:
  Enabled: false

# Ignore "Avoid using {...} for multi-line blocks"
Style/BlockDelimiters:
  Enabled: false

# Ignore "Omit the default :each argument for RSpec hooks"
RSpec/HookArgument:
  Enabled: false
