# Rubocop configuration, see https://docs.rubocop.org/rubocop/configuration.html

# https://github.com/rubocop-hq/rubocop-rails
# https://github.com/rubocop-hq/rubocop-rspec
require:
  - rubocop-rails
  - rubocop-rspec

#
# Opt-in to new rules by default
#
# For more information: https://docs.rubocop.org/rubocop/versioning.html
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

#
# Specific excludes & includes
#

# Okay to have long examples in feature tests, there are usually many steps
RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*.rb'

# Okay to have more than one expectation in a single block, default: 1
RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/*.rb'

# Ignore LineLength for config files (e.g. with long secret strings)
Layout/LineLength:
  Exclude:
    - 'config/**/*.rb'

# Ignore "Block has too many lines" for specs, `RSpec.describe` blocks can be long
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# Only check "Missing top-level class documentation comment" for models
Style/Documentation:
  Include:
    - 'app/models/*.rb'

# Ignore empty lines in schema.rb. File is generated.
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

#
# Ignoring entire rules
#

# Ignore "Missing frozen string literal comment"
Style/FrozenStringLiteralComment:
  Enabled: false

# Ignore "Gems should be sorted in an alphabetical order within their section of the Gemfile"
Bundler/OrderedGems:
  Enabled: false
